### ISSUE TITLE
UX Improvement: Make user aware that Open AI Key is necessary

### ISSUE THREAD

**Issue by esau-morais** [fernandops26/mentalist-ai#1]
### Description
If you try to click the "Generate" button and do not provide a Open AI Key, nothing happens.

![image](https://user-images.githubusercontent.com/55207584/219694797-d557d03e-54e7-4399-ab41-f1c217ab25f0.png)

### Possible solutions

1. Create root page to accept the Open AI Key before accessing the `map` route
2. Alert user when Open AI key is not provided
  2.1. Dialog
  2.2. Form error

**Comment by esau-morais** [comment]
We must discuss more about the possible solutions and, if you don't mind, I'm interest on working in this issue.

**Comment by fernandops26** [comment]
@esau-morais For sure, that really helps!

**Comment by Mythie** [comment]
Resolved with the changes within #3
