### ISSUE TITLE
Main Topic

### ISSUE THREAD

**Issue by saliksik** [fernandops26/mentalist-ai#2]
Please allow us to directly generate ideas on the Main Topic without providing any subtopic at all. When we generate the main topic, it will automatically generate subtopics.

**Comment by fernandops26** [comment]
@saliksik I like the idea, just I am thinking how to provide a direction for the root topic, maybe using keywords or a few options.
I am open to ideas for this request.

**Comment by fernandops26** [comment]
Good news @saliksik , has been implemented the feature! Plus added a new option to generate subcategories.
